NODE_FILE: ./AutoGenerateExample/model-desc/ctdc_model_file.yaml
PROP_FILE: ./AutoGenerateExample/model-desc/ctdc_model_properties_file.yaml
SYNTHETIC_DATA_FILE: ./AutoGenerateExample/datagen_configs/ctdc-synthetic_data_values.xlsx
DATA_SPEC_FILE: ./AutoGenerateExample/datagen_configs/CTDC_Template-Start.yml
ID_FILE: ./AutoGenerateExample/datagen_configs/props-ctdc.yml
OUTPUT_FOLDER: ./AutoGenerateExample/example_loadsheets/