---
HeadNode:
- name: program
  count: 1
  Prefix: CTDC
  
  
#Nodes to be included in the data graph.
#Only nodes in the IncludeNodes section will be created.
#Includes nodes in the hierarchy in which they occur in the model.
IncludeNodes:
  project:
    NodeCount: 2
    Prefix: CTDC-PROJECT
  study:
    NodeCount: 4
    Prefix: CTDC-STUDY
  subject:
    NodeCount: 64
    Prefix: CTDC-SUBJECT
  demographic:
    NodeCount: 64
    Prefix: CTDC-DEMOGRAPHIC
  exposure:
    NodeCount: 128
    Prefix: CTDC-EXPOSURE
  diagnosis:
    NodeCount: 128
    Prefix: CTDC-DIAGNOSIS
  targeted_therapy:
    NodeCount: 128
    Prefix: CTDC-TARGETED-THERAPY
  surgical_procedure:
    NodeCount: 128
    Prefix: CTDC-SURGICAL-PROCEDURE
  radiological_procedure:
    NodeCount: 128
    Prefix: CTDC-RADIOLOGICAL-PROCEDURE
  subject_status:
    NodeCount: 64
    Prefix: CTDC-SUBJECT-STATUS
  specimen:
    NodeCount: 128
    Prefix: CTDC-SPECIMEN
  data_file:
    NodeCount: 256
    Prefix: CTDC-DATA-FILE
  associated_link:
    NodeCount: 8
    Prefix: CTDC-ASSOCIATED-LINK
  image_collection:
    NodeCount: 8
    Prefix: CTDC-IMAGE-COLLECTION
  therapy:
    NodeCount: 128
    Prefix: CTDC-IMAGE-COLLECTION
  principal_investigator:
    NodeCount: 8
    Prefix: CTDC-PRINCIPAL-INVESTIGATOR
#Properties for which synthetic values need to be created.
#Assumption: property names are duplicated among node types, ie, a property never belongs
#to more than one node type.

IncludeProperties:
  program:
    - program_name #11444542
    - program_short_name #11459801

  project:
    - project_name #11459804
    - project_short_name #11459806

  study:
    - study_name #11459810
    - study_short_name #11459812
    - study_id
    - study_description
    - study_type #11160683
    - dates_of_conduct

  principal_investigator:
    - principal_investigator_first_name #10624731
    - principal_investigator_last_name #10624733
    - principal_investigator_middle_name #10624732
    - principal_investigator_orcid_id #10624734

  associated_link:
    - associated_link_name
    - associated_link_url

  image_collection:
    - image_collection_name
    - image_type_included
    - image_collection_url
    - repository_name
    - collection_access
  
  subject:
    - subject_id
    - biomarker_results_available
    - radiology_report_available #6944764
    - radiology_images_available
    - histology_images_available

  demographic:
    - demographic_id
    - sex
    - reported_gender #10748236
    - race
    - ethnicity
    - ncbi_taxonomy_id #10543100
    - ncbi_taxonomy_name #10543082

  exposure:
    - exposure_id
    - environmental_exposure_type #11256813
    - carcinogen_exposure
  
  diagnosis:
    - diagnosis_id
    - icd_10_disease_code #11479873
    - meddra_disease_code
    - ctep_disease_code
    - snomed_disease_code # this is disease plus stage I think
    - diagnosis_date # quantified in days indexed to date of trial enrollment
    - icd_o_primary_site #11341616
    - primary_disease_site
    - tumor_grade #11325685
    - subject_age_at_diagnosis #10609539

  targeted_therapy:
    - targeted_therapy_id
    - targeted_therapy #6400634

  therapy:
    - therapy_id
    - therapy #6400634

  surgical_procedure:
    - surgical_procedure_id
    - surgical_procedure_name #6411539

  radiological_procedure:
    - radiological_procedure_id
    - radiological_procedure_name #6411539

  subject_status:
    - subject_status_id
    - survival_status #7050072
    - primary_cause_of_death #6421593
    - off_study
    - off_study_reason #6355981

  specimen:
    - specimen_id
    - parent_specimen_id
    # - days_from_diagnosis_to_specimen_collection #11253404
    # - diagnosis_date # from the CMB perspective, this is supposedly equivalent to the above, but because of the way this date is indexed to enrollment date, it should not be a specimen property
    # - days_from_first_subject_visit_to_specimen_collection #11248874
    # - days_from_first_treatment_to_specimen_collection #11250807
    # - days_from_initial_genomic_sequencing_to_Specimen_collection #11250807
    # - days_from_recurrence_to_specimen_collection #11251133
    # - days_from_specimen_collection_to_initial_pathologic_diagnosis #11253404
    - collection_date # from the CMB perspective, this is equivalent to the above, with collection date indexed to enrollment date caDSR 6401821
    - icd_o_3_tissue_morphology # 11326261
    - obi_specimen_type #11253427 not a good match to the caDSR term referenced by the CDE's ID
    - specimen_category # confusingly close to the CMB Catalog Site's "Tissue Category" i.e. the indicator as to normal vs primary vs metastatic, but acceptable terms for caDSR 7069877, quoted as a reference for "specimen category" uses terms that do not relate to "tissue category"
    - type_of_tissue #caDSR 7003892 this looks very much like the CMB Catalog Site's "Tissue Category"
    - anatomical_collection_site
    - parent_specimen_type
    - specimen_type
    - tissue_category # this would be the Catalog Site's "Tissue Category" i.e. the indicator as to normal vs primary vs metastatic, which appears within at least two of the DDs as Tissue Type
    - assessment_timepoint # this appears to be the Catalog Site's "Collection Timepoint" caDSR 7065963

  data_file:
    - data_file_name #11284037
    - data_file_type
    - data_file_description #11280338
    - data_file_format #11416926
    - data_file_size #11479876
    - data_file_checksum_value #11480133
    - data_file_checksum_type #11475057
    - data_file_compression_status #11387114
    - data_file_uuid
    - data_file_location

#Relationship specifications. For example: how many studies per program; how many cases per studies.
# This also includes specifications on how these node counts should be generated.
# 1. SrcNodeCount: fixed, indicates that the "count" variable holds the counts.
# 2. SrcNodeCount: random, indicates that counts are generated from a drawing from a uniform distribution 
# 3. All relationships among the included nodes will automatically be created.
# 4. Do not specify relationships between nodes of the same type, e.g between two samples, two visits etc.

RelationshipSpecs:
  program:
    project:
      SrcNodeCount: fixed
    study:
      SrcNodeCount: fixed
  project:
    study:
      SrcNodeCount: fixed
    principal_investigator:
      SrcNodeCount: fixed
    data_file:
      SrcNodeCount: fixed
    associated_link:
      SrcNodeCount: fixed
    image_collection:
      SrcNodeCount: fixed
  study:
    subject:
      SrcNodeCount: fixed
    data_file:
      SrcNodeCount: fixed
    associated_link:
      SrcNodeCount: fixed
    image_collection:
      SrcNodeCount: fixed
    principal_investigator:
      SrcNodeCount: fixed
  subject:
    data_file:
      SrcNodeCount: fixed
    demographic:
      SrcNodeCount: fixed
    exposure:
      SrcNodeCount: fixed
    diagnosis:
      SrcNodeCount: fixed
    targeted_therapy:
      SrcNodeCount: fixed
    therapy:
      SrcNodeCount: fixed
    surgical_procedure:
      SrcNodeCount: fixed
    radiological_procedure:
      SrcNodeCount: fixed
    subject_status:
      SrcNodeCount: fixed
    specimen:
      SrcNodeCount: fixed
  specimen:
    data_file:
      SrcNodeCount: fixed

