name: DataGen
on:
  push:
    # Be sure to set "branches" to the branch where a push will trigger the example file creation 
    branches: 
      - main
env:
  # CONFIG_DIR is the directory where the Bento Data Generator configuration file lives
  CONFIG_DIR: ./AutoGenerateExample/datagen_configs
  # WORKING DIR is where GitHub Actions does its work.  This doesn't need to be changed, but can be
  WORKING_DIR: ./AutoGenerateExample
  # DESTINATION_DIR is the repository directory where you want the completed example files placed
  DESTINATION_DIR: example_loadsheets
  # REPOSITORY is the data model repository
  REPOSITORY:  pihltd/AutoGenerateExample
  # ZIP_FILE is the name for the zip archive
  ZIP_FILE: ExampleSubmissionSheets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data generator
        uses: actions/checkout@main
        with:
          repository: CBIIT/bento-data-generator
          path: ./bento-data-generator
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./bento-data-generator/requirements.txt
      - name: Checkout bento common
        uses: actions/checkout@master
        with:
          repository: CBIIT/bento-common
          path: ./bento-data-generator/bento
      - name: Checkout data model
        uses: actions/checkout@main
        with:
          #repository: pihltd/AutoGenerateExample
          #path: ./AutoGenerateExample
          repository: ${{ env.REPOSITORY }}
          path: ${{ env.WORKING_DIR }}
      - name: Run data generator
        run: python ./bento-data-generator/bento-synthetic-data-generator.py $CONFIG_DIR/datagen_config_1.yml
        #run: python ./bento-data-generator/bento-synthetic-data-generator.py ./AutoGenerateExample/datagen_configs/datagen_config_1.yml
        #run: python ./bento-data-generator/bento-synthetic-data-generator.py ./AutoGenerateExample/datagen_configs/datagen_config.yml
        # PUT ZIP STUFF HERE
      - name:  Zip the generated files
        run: zip -r $WORKING_DIR/$DESTINATION_DIR/$ZIP_FILE.zip . --no-dir-entries --include  $WORKING_DIR/*.tsv
      - name: Commit and push
        run: |
          git config --global user.name 'Todd Pihl'
          git config --global user.email 'todd.pihl@nih.gov'
          git add ./$DESTINATION_DIR/*.zip
          git commit -m "Auto Data Generation" 
          git push
        #working-directory: ./AutoGenerateExample
        working-directory: ${{ env.WORKING_DIR }}
        # # git add ./example_loadsheets/*  Original Line 43.
    