name: DataGen
on:
  push: 
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data generator
        uses: actions/checkout@main
        with:
          repository: CBIIT/bento-data-generator
          path: ./bento-data-generator
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./bento-data-generator/requirements.txt
      - name: Checkout bento common
        uses: actions/checkout@master
        with:
          repository: CBIIT/bento-common
          path: ./bento-data-generator/bento
      - name: Checkout data model
        uses: actions/checkout@main
        with:
          repository: pihltd/AutoGenerateExample
          path: ./AutoGenerateExample
      - name: Run data generator
        #run: python ./bento-data-generator/bento-synthetic-data-generator.py ./AutoGenerateExample/configs/datagen_config_1.yml
        run: python ./bento-data-generator/bento-synthetic-data-generator.py ./AutoGenerateExample/configs/datagen_config.yml

      - name: Commit and push
        run: |
          git config --global user.name 'Todd Pihl'
          git config --global user.email 'todd.pihl@nih.gov'
          git add ./example_loadsheets/*
          git commit -m "Auto Data Generation" 
          git push
        working-directory: ./AutoGenerateExample
    