name: DataGen
on:
  push: 
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data generator
        uses: actions/checkout@main
        with:
          repository: CBIIT/bento-data-generator
          path: ./bento-data-generator
          #run: python -m pip3 install -r ./bento-data-generator/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./bento-data-generator/requirements.txt
      - name: Checkout data model
        uses: actions/checkout@main
        with:
          repository: pihltd/AutoGenerateExample
          path: ./AutoGenerateExample
      - name: Run data generator
        run: python ./bento-data-generator/bento-synthetic-data-generator.py ./AutoGenerateExample/configs/datagen_config.yml